### ISSUE TITLE
Do benchmark with JIT'ed next() and ipairs()

### ISSUE THREAD

**Issue by ExtReMLapin** [GitSparTV/LuaJIT-Benchmarks#1]
Title : 

Using https://github.com/LuaJIT/LuaJIT/pull/275 and lua coded pairs()

**Comment by GitSparTV** [comment]
Additional test was added in commit https://github.com/GitSparTV/LuaJIT-Benchmarks/commit/54e9a4ed8c4e4013a33051daf81a387d7b54529d.
Thank you.
