### ISSUE TITLE
[test2] Instructions outside of the hot loop are counted

### ISSUE THREAD

**Issue by Totktonada** [GitSparTV/LuaJIT-Benchmarks#3]
https://gitspartv.github.io/LuaJIT-Benchmarks/#test2

The comparison tells the following:

> Global table indexing: 38 instructions total.
> Local: 18 instructions total.
> <details>
> <summary>Diff</summary>
>
> ```diff
>   mov dword [0x24660410], 0x1
>   movsd xmm7, [rdx+0x40]
>   cvttsd2si eax, xmm7
>   xorps xmm6, xmm6
>   cvtsi2sd xmm6, eax
>   ucomisd xmm7, xmm6
>   jnz 0x7ffa543c0010        ->0
>   jpe 0x7ffa543c0010        ->0
>   cmp eax, 0x7ffffffe
>   jg 0x7ffa543c0010 ->0
>   cvttsd2si edi, [rdx+0x38]
>   cmp dword [rdx+0x14], -0x09
> - jnz 0x7ffa543c0010        ->0
> - cmp dword [rdx+0x10], 0x2467f788
> - jnz 0x7ffa543c0010        ->0
> - mov ebp, [0x2467f790]
> - cmp dword [rbp+0x1c], +0x3f
> - jnz 0x7ffa543c0010        ->0
> - mov ebx, [rbp+0x14]
> - mov rsi, 0xfffffffb24665fd8
> - cmp rsi, [rbx+0x518]
> - jnz 0x7ffa543c0010        ->0
> - cmp dword [rbx+0x514], -0x0c
>   jnz 0x7ffa543c0010        ->0
> + cmp dword [rdx+0x18], 0x2466aca0
> - mov edx, [rbx+0x510]
> - cmp dword [rdx+0x1c], +0x1f
> - jnz 0x7ffa543c0010        ->0
> - mov ecx, [rdx+0x14]
> - mov rsi, 0xfffffffb24666548
> - cmp rsi, [rcx+0x230]
> - jnz 0x7ffa543c0010        ->0
> - cmp dword [rcx+0x22c], -0x09
> - jnz 0x7ffa543c0010        ->0
> - cmp dword [rcx+0x228], 0x24666520
>   jnz 0x7ffa543c0010        ->0
>   add edi, +0x01
>   cmp edi, eax
>   jg 0x7ffa543c0014 ->1
> ```
> </details>

The benchmark counts overall instructions, not only the hot loop. The real performance is the same for both variants (at least for this particular test).

```lua
-- luajit-bench-2-v1.lua
local function test()
    local acc = 0
    for i = 1, 10^8 do
        acc = acc + math.sin(3.14)
    end
    return acc
end

print(test())
```

```lua
-- luajit-bench-2-v1.lua
local s = math.sin

local function test()
    local acc = 0
    for i = 1, 10^8 do
        acc = acc + s(3.14)
    end
    return acc
end

print(test())
```

Curious fact: if I change sin(3.14) to sin(i), the loops in both code variants (and so timings) are still equivalent.

You can easily look at both variants of IR/asm using luajit.me (just replace 10^8 with 10^5 or something like so).

![image](https://user-images.githubusercontent.com/92749/202477891-c777cd50-15bd-41a5-9d6b-44e25814c5da.png)

![image](https://user-images.githubusercontent.com/92749/202478150-bcd12b52-3543-4a78-b915-23df8e05bf93.png)

Side note: It is hard to spot that the diff on the web page shows the code outside of the hot loop. I worth to show more context in the diff at least.

**Comment by GitSparTV** [comment]
Thanks for the interest of this project.
I counted instructions outside as well because the subject of measurement is the whole function including JIT prerequisites.
But I agree this is unfair. In the 3rd edition I tried to take more real rather than synthetic tests.  Counting instructions at this moment is not the best way for me.

Btw, I see you work in Tarantool.
I'm from Moscow and looking for job opportunities if you have someone to send this or just connect me :)
https://www.linkedin.com/in/linkedsavva

**Comment by GitSparTV** [comment]
@Totktonada Closing as third edition won't have instructions difference (for now). But I will remember this.

**Comment by Totktonada** [comment]
I don't know how the 3rd edition will look like, but I would highlight the general point behind the test2 problem. We have a two level model:

* The goal is to deduce general recommendations on whether particular microoptimizations worth to do.
* Each test aims to show a difference in performance with and without a particular microoptimization in an application code. Here we have the first decision point: which tests better do that.
* In assumption that each test represents a microoptimization influence in the best way, we define how to compare test results with/without the microoptimization. It is the second decision point.

You said that you're working on the first point. That's nice. I want to emphasise the second: if both variants of a test show the same execution time, our comparison model should say that they're equivalent. Any metrics we'll introduce should met this criteria. That's where a difference in instructions count doesn't work.

(In my opinion the best metric is the execution time itself, but some work should be done to get stable results. Some typical steps are mentioned [here](https://github.com/tarantool/tarantool/issues/4774#issuecomment-585185126), [here](https://github.com/tarantool/tarantool/issues/4774#issuecomment-585188382), [here](https://github.com/tarantool/go-tarantool/blob/7e86795514b0e0637372bee473deb8eaefb51401/CONTRIBUTING.md#recommendations-for-how-to-achieve-stable-results) and [here](https://github.com/tarantool/tarantool/wiki/User:Totktonada#estimate-noise-in-performance-measurements).)

I appreciate your interest in Tarantool. We have a page with open positions on the [website](https://www.tarantool.io) (Contants -> Careers). If you want to reach me privately, leave a message in Telegram (@Totktonada) or drop a letter to my email (alexander.turenko@tarantool.org).
